Thread 1 killed on uncaught exception Uncaught_exception_handler.CallbackExn
<<<<<<< HEAD
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 30, characters 2-79
Called from Thread.create.(fun) in file "thread.ml", line 52, characters 8-14
||||||| 121bedcfd2
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
=======
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", lines 28-30, characters 12-45
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/trunk
[thread 2] caught Uncaught_exception_handler.CallbackExn
<<<<<<< HEAD
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 30, characters 2-79
Called from Thread.create.(fun) in file "thread.ml", line 52, characters 8-14
||||||| 121bedcfd2
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
=======
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", lines 28-30, characters 12-45
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/trunk
Thread 2 killed on uncaught exception Uncaught_exception_handler.CallbackExn
<<<<<<< HEAD
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 30, characters 2-79
Called from Thread.create.(fun) in file "thread.ml", line 52, characters 8-14
||||||| 121bedcfd2
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
=======
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", lines 28-30, characters 12-45
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/trunk
Thread 2 uncaught exception handler raised Uncaught_exception_handler.UncaughtHandlerExn
Raised at Uncaught_exception_handler.handler in file "uncaught_exception_handler.ml", line 26, characters 2-17
Called from Thread.create.(fun) in file "thread.ml", line 61, characters 10-41
[thread 3] caught Uncaught_exception_handler.CallbackExn
<<<<<<< HEAD
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 30, characters 2-79
Called from Thread.create.(fun) in file "thread.ml", line 52, characters 8-14
||||||| 121bedcfd2
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", line 28, characters 12-113
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
=======
Raised at Uncaught_exception_handler.fn in file "uncaught_exception_handler.ml", lines 28-30, characters 12-45
Called from Thread.create.(fun) in file "thread.ml", line 48, characters 8-14
>>>>>>> ocaml/trunk
